version: "3.5"

services:
  frontend:
    image: node:16.15.1-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    entrypoint: "npm start"
  backend:
    image: node:16.15.1-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    entrypoint: "npm run dev"